### ISSUE TITLE
Decompression fails

### ISSUE THREAD

**Issue by marnovandermaas** [gktrk/marss-riscv-images#1]
I tried following the readme on my system (Ubuntu 18.04 with XZ Utils 5.2.2) and got stuck on the decompression step. This is the error I get:

```
$ xz -d -k -T 0 riscv32.img.xz
xz: riscv32.img.xz: File format not recognized
```

**Comment by AshwinKrishn** [comment]
+1 
Decompress fails. Can you update the repo ?

**Comment by marnovandermaas** [comment]
Ok, I found the issue. I needed to install `git-lfs` and then use the large file storage command to clone the repository:

```
$ apt install git-lfs
$ git lfs clone https://github.com/gktrk/marss-riscv-images.git
```

It might be good to mention the `git lfs clone` command in the how-to-use section, even though you mention `git-lfs` in the prerequisites.

Alternatively, people can use the images available here: https://cs.binghamton.edu/~marss-riscv/marss-riscv-images.tar.gz
